import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Head } from "next/document";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import StyledComponentsRegistry from "@/lib/registry";
import { StyleProvider } from "@ant-design/cssinjs";
import StyleLayout from "./stylelayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <StyledComponentsRegistry>
            <StyleLayout>
              {children}
              </StyleLayout>
          </StyledComponentsRegistry>
        </AntdRegistry>
      </body>
    </html>
  );
}
